package com.example.lgauthservice.shared.constants;

public interface KeyConfigConstants {
    String TS_IMAGE_ID = "TS_IMAGE_ID";
    String TS_HEADERS = "TS_HEADERS";
    String TS_VERIFY_FACE_LIVENESS_SYNC = "TS_VERIFY_FACE_LIVENESS_SYNC";
    String TS_VERIFY_PORTRAIT_SANITY_SYNC = "TS_VERIFY_PORTRAIT_SANITY_SYNC";
    String TS_CLIENT_SETTINGS = "TS_CLIENT_SETTINGS";
    String TS_UPLOAD_FILES = "TS_UPLOAD_FILES";

    String KEY_AUTH_SERVICE_API_VERIFY_TOKEN = "AUTH_SERVICE_API_VERIFY_TOKEN";
    String VA_API_UPDATE_BEAUTY_ACCOUNT_HOLD = "VA_API_UPDATE_BEAUTY_ACCOUNT_HOLD";
    String VA_API_GET_BEAUTY_ACCOUNT_HOLD= "VA_API_GET_BEAUTY_ACCOUNT_HOLD";
    String VA_API_GET_BEAUTY_ACCOUNT_SUGGEST= "VA_API_GET_BEAUTY_ACCOUNT_SUGGEST";
    String VA_API_OPEN_BEAUTY_ACCOUNT= "VA_API_OPEN_BEAUTY_ACCOUNT";
    String VA_API_BEAUTY_ACCOUNT_UNHOLD= "VA_API_BEAUTY_ACCOUNT_UNHOLD";

    String KEY_CONSENT_TNC_API_GET_TNC_URL = "CONSENT_TNC_API_GET_TNC_URL";
    String KEY_MAGNET_CONSENT_API_CREATE_CUSTOMER_URL = "MAGNET_CONSENT_API_CREATE_CUSTOMER_URL";
    String KEY_MAGNET_CONSENT_MSB_API_KEY = "MAGNET_CONSENT_MSB_API_KEY";
    String KEY_DIP_REFERRAL_API_URL = "DIP_REFERRAL_API_URL";
    String KEY_DIP_MSB_API_KEY = "DIP_MSB_API_KEY";
    String KEY_DIP_INTERNAL_TOKEN = "DIP_INTERNAL_TOKEN";
    String NEW_EKYC_API_INIT_TRANS_URL = "NEW_EKYC_API_INIT_TRANS_URL";
    String NEW_EKYC_HEADERS = "NEW_EKYC_HEADERS";
    String NEW_EKYC_API_TRANS_RESULT_URL = "NEW_EKYC_API_TRANS_RESULT_URL";
    String NEW_EKYC_API_USER_CONSENT_URL = "NEW_EKYC_API_USER_CONSENT_URL";
    String CBK_MINI_APP_DEEP_LINK = "CBK_MINI_APP_DEEP_LINK";
    String NEW_EKYC_API_UPLOAD_IMAGE_URL = "NEW_EKYC_API_UPLOAD_IMAGE_URL";
    String NEW_EKYC_API_SET_STATUS_URL = "NEW_EKYC_API_SET_STATUS_URL";

    String ACCOUNT_TRANSACTION_LIMIT = "ACCOUNT_TRANSACTION_LIMIT";


    String NEW_USER_SERVICE_DOMAIN_URL = "NEW_USER_SERVICE_DOMAIN_URL";
    String NEW_USER_SERVICE_UPDATE_USER_PATH = "NEW_USER_SERVICE_UPDATE_USER_PATH";
    String NEW_USER_SERVICE_GET_BY_ID_PATH = "NEW_USER_SERVICE_GET_BY_ID_PATH";
    String NEW_USER_SERVICE_CREATE_USER_TRANSACTION_VNEID_PATH = "NEW_USER_SERVICE_CREATE_USER_TRANSACTION_VNEID_PATH";
    String NEW_USER_SERVICE_UPDATE_USER_TRANSACTION_VNEID_PATH = "NEW_USER_SERVICE_UPDATE_USER_TRANSACTION_VNEID_PATH";
    String NEW_USER_SERVICE_GET_USER_TRANSACTION_VNEID_PATH = "NEW_USER_SERVICE_GET_USER_TRANSACTION_VNEID_PATH";
}
